# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on: 
  pull_request:
    branches: [ Staging ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup node.js 🛎️
      - uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build       
          env:
           CI: false

  deploymentStaging:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://github.com 
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "Staging"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "feature, automated pr"
        pr_title: "Staging"
